### ISSUE TITLE
The use of final keyword is prohibited

### ISSUE THREAD

**Issue by lenaorobei** [magento/magento-coding-standard#10]
### Rule
The use of `final` keyword is prohibited.

### Reason
Magento is a highly extensible and customizable platform. 
Final classes and method are not compatible with plugins and proxies. 

### Implementation
Detect `T_FINAL` token in the file.
Sniff should replace corresponding [PHPMD rule](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/FinalImplementation.php).

**Comment by thomas-kl1** [comment]
@lenaorobei 

If you want Magento to be an highly extensible and customizable platform, you should allow the "final" keyword...

That article sum it up fine: https://ocramius.github.io/blog/when-to-declare-classes-final/

Good abstraction and extensibility come from good architecture... "Final" is also a good way to promote composition, what Magento is trying to push
