### ISSUE TITLE
MEQP or Magento Coding Standards?

### ISSUE THREAD

**Issue by paul-gene** [magento/magento-coding-standard#100]
Which is the preferred ruleset?

I understand MEQP will be updated soon and lose M2 support, however, I also noticed that MEQP ruleset seems to suggest usage of `<?php echo` instead of short-hand notation, but MCS ruleset suggests `<?=` instead.

Which is it?

**Comment by lenaorobei** [comment]
@paul-gene, the answer is **Magento Coding Standard**.
Here is the link to [Magento DevDocs](https://devdocs.magento.com/guides/v2.3/coding-standards/code-standard-php.html).

MEQP will serve for Magento 1.x code only.
