### ISSUE TITLE
Single line @inheritdoc shouldn't be allowed?

### ISSUE THREAD

**Issue by celorodovalho** [magento/magento-coding-standard#113]
### Description
Accord with https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#2-conventions-used-in-this-document, we can use single line annotations for @inheritdoc DocBlocks. But, there is no mention about "single line / inline @inheritdoc" in Magento Guidelines (https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc), and if run the phpcs from Magento, I got a exception about:
```
You must use "*/" to end a function comment; found "/** @inheritdoc */"
```

### Expected behavior
Allowance to use single line / inline DocBlocks to @inheritdoc

### Benefits
Conformity with php-fig default standards

### Additional information
If I use:
```php
    /**
     * @inheritdoc
     */
```
Like described in documentation () I still get a error:
```
The incorrect inherit doc tag usage. Should be {@inheritdoc}
```
Why? If I want to inherit the entire doc block from the parent method?

**Comment by orlangur** [comment]
Thanks @lenaorobei. Inheritdoc is currently under process of complete removal in Vinai devdocs PR.

**Comment by lenaorobei** [comment]
@celorodovalho please refer this PR for more details https://github.com/magento/devdocs/pull/4425

**Comment by lenaorobei** [comment]
@celorodovalho mentioned PR is merged DevDocs are reflecting Magento recommendation.
https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html

We also have an issue to implement corresponding rule and replace with the existing one https://github.com/magento/magento-coding-standard/issues/54

If you feel like DevDocs contain wrong information please do not hesitate to open [magento/devdocs](https://github.com/magento/devdocs) issue.
