### ISSUE TITLE
Space before colon required in phtml files when using alternative syntax for control structures?

### ISSUE THREAD

**Issue by hostep** [magento/magento-coding-standard#118]
### Description
Hi

This is more a question or a start of a discusion around the fact that currently a space is required before a colon in phtml files when using the [alternative syntax for control structures](https://www.php.net/manual/en/control-structures.alternative-syntax.php).

So currently Magento code standards expects us to use this format in phtml files:
```php
<?php if ($something) : ?>
    <!-- do something -->
<?php else : ?>
    <!-- do something else -->
<?php endif; ?>
```

I'm wondering why this is required at this moment? Was there a reason for requiring it like this? Or did it just happen because it is the default setting of the PHP_CodeSniffer project?
Because it looks very ugly (personal opinion), other php projects don't enforce this syntax, a lot of php tutorials/samples don't use it, and it's also not part of any php coding standard as far as I'm aware?

I would rather see this format:
```php
<?php if ($something): ?>
    <!-- do something -->
<?php else: ?>
    <!-- do something else -->
<?php endif; ?>
```

This could be changed with this option:
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties#squizcontrolstructurescontrolsignature

I'm seeing a lot of files [being changed recently](https://github.com/magento/magento2/commit/8698a6959f5163ee26b4a900e8749e24ca33e319) in the `2.3-develop` branch whereas in Magento 2.3.2 this syntax wasn't being enforced yet. So it feels like somebody made this decision to enforce this but I can't find the reasoning behind it.

Not sure if this would make a chance to get changed?
No big deal if not, just wanted to bring this up 🙂

Thanks!

**Comment by chris-pook** [comment]
I agree with this, the additional space adds nothing really and is very inconsistent across the codebase.

**Comment by hostep** [comment]
@lenaorobei: any updates here?

If this gets approved, it best happens before Magento 2.3.3 gets released, otherwise a lot of files will get changed to the other format and then again in 2.3.4 to this new proposal (if approved). It would be nice if all changes could happen in a single Magento release if possible.
This makes figuring out what changed in between releases easier as fewer files will have been updated.

Thanks!

**Comment by lenaorobei** [comment]
@hostep I'm fine with this change, but unfortunately we can be done for 2.3.4 and later. We have code freeze for 2.3.3 now.

@paliarush are you ok with it?
