### ISSUE TITLE
[New Rule] No imports from static tests namespaces

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento-coding-standard#142]
### Rule
I suggest to add one rule that will check that there is no imports from static tests namespaces.

### Reason
Time to time we're getting issue with running tests on PRs in magento/magento2 repository because someone imported `\Magento\Tests\NamingConvention\true\string` by mistake. As result - we have "No build reports available" for "Database Compare build", "Functional Tests build", "Sample Data Tests build" while Static tests are shown as "failing" but in results - we don't really have reason. Example: https://github.com/magento/magento2/runs/214712913

### Implementation
Check that all files in all modules do not contains any imports from `\Magento\Tests\NamingConvention` namespace

**Comment by lenaorobei** [comment]
As per https://github.com/magento/architecture/issues/290 it was decided to prohibit any `Magento\Tests` imports in modules.

**Comment by konarshankar07** [comment]
Hello @lenaorobei ,
What should be the `severity` and `type` for this new rule?
Thanks

**Comment by lenaorobei** [comment]
@konarshankar, severity - 8, type - warning.
