### ISSUE TITLE
[New rule] Do not use in_array

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento-coding-standard#143]
### Rule
`in_array` creating performance issue in many places when it used a lot of times.

### Reason
Performance diff: https://stackoverflow.com/questions/13483219/what-is-faster-in-array-or-isset

It causes performance issues: 
- https://github.com/magento/magento2/pull/24677
- https://github.com/magento/magento2/issues/20966
- https://github.com/magento/magento2/pull/4088

**Comment by lenaorobei** [comment]
I would say even: "Do not use `in_array` in the loop". 
`ForeachArrayMergeSniff` can be extended and renamed in order to perform this check 
https://github.com/magento/magento-coding-standard/blob/develop/Magento2/Sniffs/Performance/ForeachArrayMergeSniff.md

**Comment by ihor-sviziev** [comment]
> I would say even: "Do not use `in_array` in the loop".
> `ForeachArrayMergeSniff` can be extended and renamed in order to perform this check
> https://github.com/magento/magento-coding-standard/blob/develop/Magento2/Sniffs/Performance/ForeachArrayMergeSniff.md

We could start from this.

But actually in most cases it’s quite obvious that it could cause performance issues in a loop, while real performance issues becoming on integration phases, when one method that contains in_array for few elements  just called few thousands times. Example related to magento https://github.com/tedious/JShrink/pull/90

**Comment by lenaorobei** [comment]
The issue was discussed during the https://github.com/magento/architecture/issues/290 and it was decided to not to introduce rule that may cause false-positive findings because its static nature (cannot measure actual performance).

**Comment by andrey-legayev** [comment]
Sure, in_array() is a general practice in PHP and typical answer to question "how to kill performance"
Should I revoke my pull requests?

**Comment by lenaorobei** [comment]
@andrey-legayev you are very welcome to join next public architecture discussion and share your thoughts. We are open to any improvements in case they provide a real value.

**Comment by andrey-legayev** [comment]
How to optimize magento2 performance:

 - run profiler
 - look for in_array
 - fix it

This is what I do during last 2 weeks.
How to prevent people not to use in_array() for 2000 elements? sometimes in loop...

**Comment by lenaorobei** [comment]
I do understand you point and the reason that stays behind the use of `in_array` in loop.
Coding standard rules perform static file analysis and know nothing about array size. The reason why we closed this issue is because PHP CodeSniffer in not appropriate tool to perform such kind of check.

**Comment by buskamuza** [comment]
@andrey-legayev , I'd better promote better practices of using loops in general. There are many things that can kill performance, and `in_array()` is not the only one. IMO, a real human (developer) should think about performant implementation of loops. A general rule is usually:
* remove anything repeatable outside of a loop

This is not about `in_array()` calls, and it's hard to cover all use cases with static checks. For example, retrieving value from another service. Anything that doesn't rely on the array item we are iterating, should be move outside of the loop.

In the same time if you have an array of two items you're iterating through, and you do `in_array()` for another array of three items, most likely you don't care about performance here. And if `in_array()` adds readability, I'd rather keep it there.

**Comment by andrey-legayev** [comment]
I measured in_array() performance for 1 element and isset() is still be faster.
Sure, I had to run code 100k times to see time difference, but if you use it in some base class of framework for.. readability? and then call it through 20 lines of call stack 200k times. Does it make sense? IMO not.
But feel free to use it for readability.

**Comment by andrey-legayev** [comment]
For example:
[Magento\Framework\Module\ModuleList::sortBySequence()](https://github.com/magento/magento2/blob/2.3.2/lib/internal/Magento/Framework/Module/ModuleList/Loader.php#L151)
I'm sure in_array() is used inside _double_ loop for readability. Performance isn't needed there, readability is better.

**Comment by lenaorobei** [comment]
@andrey-legayev I'm afraid, we are talking about different things there. Let me try to explain. There are two statements we are trying to mix: 
- `in_array` in loop causes performance issues. Indeed, issues that you provided need to be fixed, there is no discussion regarding this and no objections. Hope, we are on the same page regarding this.
- Static check for the `in_array` in loop detection. Current issue proposes to implement PHP CodeSniffer rule for `in_array` in loop detection. And here we have contra-versional thoughts, because static detection uses tokens and does not 100% mean performance issue.

That's why it was proposed to investigate and find more appropriate tool for such check.
