### ISSUE TITLE
Usage of $this in template file

### ISSUE THREAD

**Issue by rafaelstz** [magento/magento-coding-standard#156]
### Steps to reproduce
1. Check the contact form phtml
2. There is a warning message regarding: `$this->helper`

### Expected result

1. I think it shouldn't be a warning since there is no helper method in the block.

### Actual result
1. It's showing a warning message.

**Comment by lenaorobei** [comment]
Hi @rafaelstz. This is the expected behavior. The idea behind this is that view models should be used instead. The use of helpers in general is discouraged.
