### ISSUE TITLE
Go back to semantic versioning

### ISSUE THREAD

**Issue by paul-gene** [magento/magento-coding-standard#158]
Since version 3, semantic versioning has been disregarded.

Is there a specific reason for this?

**Comment by FreekVandeursen** [comment]
See: https://github.com/magento/architecture/pull/136

**Comment by lazyguru** [comment]
+1 on this. You are breaking builds by frequently introducing what are effectively BC breaks. There should be version numbers that are then enforced with Marketplace at scheduled intervals (eg, "We recommend you adhere to version 5 but will continue to only enforce version 4 until X date").  With the current solution it's possible that the rules could get changed between the time a package is generated and when it is submitted to the Marketplace.  It's great that you want to adhere to the latest standard in core, but that doesn't scale when applied to all partners and extension developers without warning.

**Comment by lenaorobei** [comment]
Hi @paul-gene! Yes, as @FreekVandeursen mentioned there was a long thread of discussion regarding coding standard versioning.

Semantic version makes sense if we were going to support multiple release lines, for example 1.0.0, then 2.1.0 and patch to 1.0.1, but we don't. This change is the result of the decision that only one (latest) version of coding standard will be supported.
