### ISSUE TITLE
@author MUST NOT be used.

### ISSUE THREAD

**Issue by arushibansal013** [magento/magento-coding-standard#167]
### Rule

@author MUST NOT be used

### Reason

As per magento DocBlock document (https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#documentation-space)

Structure of documentation space
@author ,@category, @package, and @subpackage MUST NOT be used. Documentation is organized with the use of namespaces.

### Implementation

Need to add @author in $forbiddenTags

**Comment by cjnewbs** [comment]
@arushibansal013 I have created a PR (#204) that adds the ability to use `phpcbf` to remove automatically. Is it worth me adding `@author` in the same PR?

**Comment by fredden** [comment]
It looks like the rule was introduced here: https://github.com/magento/devdocs/commit/4165be844c0f96bdcc41b2f952668579266f1a6e

**Comment by ihor-sviziev** [comment]
I believe all the mentioned tags must not exist in the Magento core, but it should be a case for the custom extensions 

Am I right, @Vinai ?
