### ISSUE TITLE
Avoid using PHPUnit_Framework_MockObject_MockObject

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento-coding-standard#178]
### Rule
`PHPUnit_Framework_MockObject_MockObject` triggers warning

### Reason
The `PHPUnit_Framework_MockObject_MockObject` was deprecated long time ago and `\PHPUnit\Framework\MockObject\MockObject` should be used

**Comment by ihor-sviziev** [comment]
As for now I added this class to `dev/tests/static/testsuite/Magento/Test/Legacy/_files/obsolete_classes.php` as part of https://github.com/magento/magento2/pull/27519

I don't really think is's good idea to have such check in magento coding standards.

**Comment by lenaorobei** [comment]
@lbajsarowicz agree with @ihor-sviziev.
I'm closing this issue in favor of internal task [MC-33003](https://jira.corp.magento.com/browse/MC-33003) for implementing regular static test but not the part of coding standard.

**Comment by lbajsarowicz** [comment]
Thank you.
