### ISSUE TITLE
[New Rule] Slow array SHOULD NOT be used in loop

### ISSUE THREAD

**Issue by lenaorobei** [magento/magento-coding-standard#20]
### Rule

The use of slow array functions (`array_merge`) in loop is discouraged.

### Reason
Merging arrays in a loop is slow and causes high CPU usage. [Some benchmarking](https://github.com/kalessil/phpinspectionsea/issues/138#issuecomment-279457133).

**Bad example:**
``` php
    $options = [];
    foreach ($configurationSources as $source) {
        // code here
        $options = array_merge($options, $source->getOptions());
    }
```

**Good example:**
``` php
    $options = [[]];
    foreach ($configurationSources as $source) {
        // code here
        $options[] = $source->getOptions();
    }

    // PHP 5.6+
    $options = array_merge(...$options);
```

### Implementation
- Subscribe to `T_STRING` token and check if it's content is `array_merge`. 
- Try to find outer loop.
- If loop is found rase a warning (need to discuss additional logic).

```
<severity>7</severity>
<type>warning</type>
```

**Comment by lenaorobei** [comment]
We can throw a warning with incremental approach.

**Comment by Vinai** [comment]
Mixed feelings. I often use merge in a reduce function to avoid changing local state (and save a line of code).
Hope PHP optimizes for more functional patterns in future, now that FP is becoming mainstream.
Even Java now has optimized map/reduce/filter chains, and more and more languages support STM.
If PHP follows, this sniff would be outdated.
Maybe sniffs should focus on algorithmic complexity instead of Runtime implementation details.

**Comment by shochdoerfer** [comment]
Slow is a matter of definition :) In a loop with just a few iterations, you most likely won't notice that much of a difference.

**Comment by Vinai** [comment]
Exactly. That’s why focusing on big O algorithmic complexity seems like a good idea since that’s assumes scalability in the worst case scenario.
Stating this I feel stupid because I’m sure you are well aware.

**Comment by larsroettig** [comment]
Benmarks:

- https://gist.github.com/Ocramius/8399625#file-output-txt

- https://github.com/kalessil/phpinspectionsea/blob/master/docs/performance.md#slow-array-function-used-in-loop

- https://github.com/kalessil/phpinspectionsea/issues/138#issuecomment-279457133

**Comment by lenaorobei** [comment]
@buskamuza @kandy 

Need you input here.

See related PR magento/magento-coding-standard#72

**Comment by kandy** [comment]
For me, it makes sense to have this rule

**Comment by larsroettig** [comment]
Hi @kandy, 
 sense yes but if you look to findings maybe there are some false positives

**Comment by kandy** [comment]
@larsroettig, Definitely, there are some false positives and the warning is a good signal to review such places.

**Comment by lenaorobei** [comment]
Implemented in https://github.com/magento/magento-coding-standard/pull/72
