### ISSUE TITLE
Cannot install v8 due to requirements

### ISSUE THREAD

**Issue by oneserv-heuser** [magento/magento-coding-standard#235]
It's impossible to install version 8 of this package in combination with magento as with update 8 this package now requires ["webonyx/graphql-php": "^14.9"](https://github.com/magento/magento-coding-standard/blob/05c75c0bc195621f3053d9270c75c8e7ea88ae66/composer.json#L13) and magento itself requires [ "webonyx/graphql-php": "^0.13.8"](https://github.com/magento/magento2/blob/21aa619fb497556d5f948fc911dcd04ab9dc16e6/composer.json#L79).

Why is this module using a newer version of webonyx/graphql-php as magento?

**Comment by ihor-sviziev** [comment]
In Magento it will be updated as well in https://github.com/magento/magento2/pull/33858

**Comment by andrewbess** [comment]
Hello @oneserv-heuser 
Thank you for your report.
The `magento-coding-standard` v8 will be delivered together with `webonyx/graphql-php` 14.9.0.

**Comment by lamasfoker** [comment]
As today none magento release use the `14.9` version of `webonyx/graphql-php`, see the [2.4.3-p2 composer.json](https://github.com/magento/magento2/blob/2.4.3-p1/composer.json#L82), I think people can install only `v6` of `magento/magento-coding-standard`

**Comment by ihor-sviziev** [comment]
@lamasfoker, yeah, that's true, but 2.4.4 will have the ability to install the current coding standards.

**Comment by lamasfoker** [comment]
Yes, I know @ihor-sviziev but I have to wait for 8 march and update Magento to the latest version. I think that decoupling `magento/magento-coding-standard` from the dependencies of the project is better. 
It is possible to commit to my project only `Magento2/ruleset.xml` file and run
```shell
phpcs --standard=/path/to/ruleset.xml app
```
as the [phpcs docu claim](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset)?
