### ISSUE TITLE
Wrong checking of the short descriptions in the class properties

### ISSUE THREAD

**Issue by andrewbess** [magento/magento-coding-standard#268]
### Preconditions

1. Wrong checking of the short descriptions in the class properties when code sniffer checks old class in Magento using magento-coding-standard v9 (v8 checks it correctly)
<img width="1504" alt="wrong-checking" src="https://user-images.githubusercontent.com/10788564/132938160-95410527-0acc-4f30-b128-be142846323c.png">
2. Perhaps it is reproduced after https://github.com/magento/magento-coding-standard/commit/146bfb099583f7ee26bbafec66fe6560eab4373a

### Steps to reproduce

1. Install magento-coding-standard v9
2. Check file that contains properties having diffs between property name and short description (for example https://github.com/magento/magento2/blob/2.4.3/lib/internal/Magento/Framework/View/Design/FileResolution/Fallback/Resolver/Simple.php)

### Expected result

<img width="1485" alt="expected-result" src="https://user-images.githubusercontent.com/10788564/132938366-83d6e2c1-3a1d-42cd-a7dc-76cdb3f622f1.png">

### Actual result

<img width="1532" alt="actual-result" src="https://user-images.githubusercontent.com/10788564/132938378-26176838-e17e-4533-b65a-4eff9b5b6af0.png">

**Comment by sivaschenko** [comment]
@andrewbess I as can see the short description in the file that was checked (https://github.com/magento/magento2/blob/2.4.3/lib/internal/Magento/Framework/View/Design/Fallback/Rule/Simple.php) does duplicate the property name. Do you have any propositions on how we can improve this sniff?

**Comment by andrewbess** [comment]
The problem has been fixed in https://github.com/magento/magento-coding-standard/pull/270
Thank you @svera 
Waiting for the next release (v10)
