### ISSUE TITLE
[New Rule] Controllers Should Implement HTTP Method Marker Interface

### ISSUE THREAD

**Issue by sprankhub** [magento/magento-coding-standard#34]
### Rule
Controllers SHOULD implement one of the HTTP method marker interfaces like `HttpPostActionInterface` (see https://github.com/magento/magento2/tree/2.3/lib/internal/Magento/Framework/App/Action).

### Reason
Source: [Magento DevDocs About Routing](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/routing.html)

### Implementation
Check for subclasses of `\Magento\Framework\App\Action\AbstractAction` or classes, which implement `\Magento\Framework\App\ActionInterface` and check if these classes also implement one of the marker interfaces.

### Important Details
This sniff should be applicable to Magento >=2.3, because older versions of Magento do not have HTTP method marker interfaces.

**Comment by lenaorobei** [comment]
Hello @sprankhub! Thanks for creating this proposal. Would you mind to join public Magento architecture meeting to discuss this rule? If you are interested please add this topic as a comment to the [corresponding GitHub issue](https://github.com/magento/architecture/issues/76).
The meeting will be held on February 20th.

**Comment by sprankhub** [comment]
I will try, but I will probably not be able to join the meeting. Could you add it to the list of new rules in your topic suggestion nevertheless @lenaorobei? Thanks!

**Comment by lenaorobei** [comment]
@sprankhub, sure. I'll add this topic.

**Comment by AlexMaxHorkun** [comment]
I've created PHPMD rule when I introduced HTTP method marker interfaces, isn't that enough?

**Comment by lenaorobei** [comment]
@AlexMaxHorkun good to know, thanks.
It's enough for core team, but right now Magneto Marketplace extensions checks doesn't use `phpmd` tool.

**Comment by lenaorobei** [comment]
This rule cannot be implemented using PHP CodeSniffer without false-positive findings.

As per [PHP Stan Proposal](https://github.com/magento/architecture/blob/master/design-documents/testing/static/phpstan.md#long-term-plan) this rule can be covered by PHPStan.

**Comment by sprankhub** [comment]
@lenaorobei could you elaborate why this is not possible without false positives?

If this can/should be covered with PHPStan, should we add this proposal somewhere else, so that we do not forget about it?
