### ISSUE TITLE
When property declared as nullable.   Wrong sniffer result for Magento2.Commenting.ClassPropertyPHPDocFormatting.Missing  

### ISSUE THREAD

**Issue by OleksiiStepanov** [magento/magento-coding-standard#340]
### Preconditions

1. php 7.4
2. version  16

### Steps to reproduce

1. create some class with `declare(strict_types=1);`
2. declare nullable property fot this class like 
```
    /**
     * @var null|string
     */
    private ?string $str;
```
### Expected result

1. No errors 

### Actual result

1.  phpcs: Magento2.Commenting.ClassPropertyPHPDocFormatting.Missing: Missing PHP DocBlock for class property.

**Comment by sergeynezbritskiy** [comment]
@magento I am working on this
