### ISSUE TITLE
[Problem] Namespace conflict with core rules 

### ISSUE THREAD

**Issue by lenaorobei** [magento/magento-coding-standard#45]
### Problem overview
The future direction of [magento/magento-coding-standard](https://github.com/magento/magento-coding-standard) project is to deliver unified Coding Standard to the Magento core. 
For backward compatibility [dev/tests/static/framework/Magento/ruleset.xml](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/static/framework/Magento/ruleset.xml) should not be removed. In this case both coding standards will have name `Magento` and PHP CodeSniffer will be not able to process it.

### Solution
Rename `Magento` [magento/magento-coding-standard](https://github.com/magento/magento-coding-standard) to `MagentoCS`. So [dev/tests/static/framework/Magento/ruleset.xml](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/static/framework/Magento/ruleset.xml) will look like:
``` xml
<ruleset name="Magento">
    <description>Custom Magento coding standard.</description>
    <rule ref="MagentoCS"/>
</ruleset>

```

**Comment by paliarush** [comment]
How about Magento2 ? Usually coding standards do not have CS suffix, e.g. PSR2

**Comment by orlangur** [comment]
@lenaorobei,

> For backward compatibility `dev/tests/static/framework/Magento/ruleset.xml` should not be removed

Please provide a rule among https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/ applicable to this case.

`Magento2` is definitely not a proper vendor name and goes against any proper versioning policy, including you recent proposal. Currently https://github.com/magento/magento-coding-standard is quite confusing as it contains "Magento Coding Standard" and "Magento2 Coding Standard" on the same page.
