### ISSUE TITLE
Individual polyfill packages should be used instead of symfony/polyfill

### ISSUE THREAD

**Issue by stof** [magento/magento-coding-standard#467]
Currently, this package depends on `symfony/polyfill` instead of the individual `symfony/polyfill-*` packages.
This package installing the whole mono-repo is discouraged as it installs much more stuff than necessary.

The Symfony team (which I'm a member of) [recommends using the individual packages](https://github.com/symfony/polyfill/tree/1.x#usage) instead. If we were starting it today, we would not even publish the `symfony/polyfill` package on Packagist at all, keeping it a development-only mono-repo.

Currently, this even triggers a weird behavior in Composer. See https://github.com/composer/composer/issues/11641

**Comment by stof** [comment]
Based on the commit that introduced it (https://github.com/magento/magento-coding-standard/commit/2ea3c393903fcbc1db310d96e0aff4bba540c4a3), the package that is needed is `symfony/polyfill-php80` as the feature used is `str_starts_with`

**Comment by hostep** [comment]
We can probably drop the polyfill requirement again, because support was dropped for PHP < 8.1 in https://github.com/magento/magento-coding-standard/commit/8d37ab7b8eb9c204abf2adcb2e637065595021c5

**Comment by stof** [comment]
in such case, the requirement is indeed useless (this is another benefit of requiring individual polyfills as it would have been clear that `symfony/polyfill-php80` is a useless dependency when requiring PHP 8+)

**Comment by fredden** [comment]
Thanks @stof and @hostep. I agree that I added the wrong dependency. Sorry about that. Let's get #468 merged to solve this.
