### ISSUE TITLE
[New Rule] LocalizedException SHOULD only be thrown in the Presentation layer

### ISSUE THREAD

**Issue by lenaorobei** [magento/magento-coding-standard#49]
### Rule
`LocalizedException` SHOULD only be thrown in the Presentation layer (Controllers, Blocks).

Source: [Technical Guidelines](https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html).

### Possible Implementation
Subscribe to the `T_THROW` token. If `LocalizedException` is thrown, check  if file path contains `Block` or `Controller.` If not, raise a warning.

**Comment by larsroettig** [comment]
Hi @lenaorobei, are also ViewModel Presentation layer missing in this List I will add this what you mean.

**Comment by larsroettig** [comment]
Close because of Impelementation does not solve it able with the new requirements with tokens

See:
magento/devdocs#3871
