### ISSUE TITLE
Change the bin directory

### ISSUE THREAD

**Issue by lenaorobei** [magento/magento-coding-standard#55]
### Preconditions
Have PHP CodeSniffer installed in the project.

### Steps to reproduce
1. Require `magento/magento-coding-standard`
2. Run `vendor/bin/phpcs -i`

### Expected result
1. `Magento` coding Standard is present in the list of installed standards.

### Actual result
1. `Magento` coding Standard is missing in the list of installed standards.

### How to Fix
Remove composer `bin-dir`, fix `scripts` to run `vendor/bin/phpcs` and change `README.md`.

**Comment by maderlock** [comment]
In addition to changing bin directory, added relative path from phpcs in vendor/bin to vendor/magento/magento-coding-standard that will be the base location phpcs needs when this repo is pulled in to a Magento 2 installation.

After this change, Magento is now included in list of installed standards both when downloaded stand-alone and as part of a Magento 2 installation.
