### ISSUE TITLE
Directories in "dev/tests/" should be excluded from some static rules

### ISSUE THREAD

**Issue by danielrenaud** [magento/magento-coding-standard#80]
### Preconditions

magento-coding-standard v1.0.1

### Steps to reproduce

1. Create some code somewhere in `dev/tests/*` that violates a rule like "Magento2.Exceptions.DirectThrow"

### Results
The `dev/tests/*` directories are not excluded, so all rules are applied, even if they are not necessary for test code.
Exactly which rules should be excluded may be up for discussion, but I would assume the same exclusions for `*/Tests/*` would apply.

**Comment by lenaorobei** [comment]
Since this Coding Standard is used not by Magento core only, I would not add such exclude because it is tight to Magento2 codebase and does not make sense for extension developers. I suggest be more generic here. Will this work for your case?
```
<exclude-pattern>*/Test/*</exclude-pattern>
<exclude-pattern>*Test.php</exclude-pattern>
```
 
@paliarush need your input here.

**Comment by danielrenaud** [comment]
This would then not apply to test framework code. However, it's not clear if test framework code should be held to all static tests or not.

**Comment by danielrenaud** [comment]
@lenaorobei Probably adding the exclusion you suggested would handle the majority of problems. Regarding test framework code, even if we did want to exclude some rules for that, it would most likely be different form the actual tests. And in that case maybe we could just be more accommodating of `phpcs:ignore` in these areas.
So I think adding the exclusion you mentioned above in places that currently have only `*/Test/*` will work.
Thanks!
