### ISSUE TITLE
codesniffer 3.4 support

### ISSUE THREAD

**Issue by sergeynezbritskiy** [magento/magento-coding-standard#84]
### Preconditions
Together with this coding standard I'm trying to use this coding standard https://github.com/slevomat/coding-standard for checking php7 features.
Unfortunatelly this library requires codesniffer ^3.4.2, but magento coding standard requires codesnifer ~3.3.0 which means less the 3.4.0.

What about supporting Codesniffer 3.4 ?

**Comment by lenaorobei** [comment]
Hi @sergeynezbritskiy that's definitely in our roadmap and there should be no issues with that. I added this issue to the community dashboard. You are vey welcome to open PR with version upgrade if you are interested in taking care of it.

One thing we need to take into account is magento dependency update as well. 
https://github.com/magento/magento2/blob/2.3-develop/composer.json#L94

**Comment by lenaorobei** [comment]
Fixed in https://github.com/magento/magento-coding-standard/pull/85
Thank you @sergeynezbritskiy!

**Comment by cmuench** [comment]
This change is good. But please keep an eye on backwards compatibility. We added the package via composer in our gitlab-ci pipeline. Every module which checks agains the latest Magento 2.3.1 is now broken.
