### ISSUE TITLE
JS, CSS, Less files checking

### ISSUE THREAD

**Issue by sergeynezbritskiy** [magento/magento-coding-standard#94]
### Rule
Now I can see that this standard works for .php and .phtml files only. Any plans regarding .js, .css, .less files support ?

**Comment by lenaorobei** [comment]
Hello @sergeynezbritskiy.

You're right, now this coding standard is designed for PHP only. For JS files Magento uses ESLint and JSCS and for Less - some custom PHPCS implementation. You can find it under `dev/tests/static` folder of Magento2 codebase.

If you have any ideas and suggestions of how to change or improve this we would be happy to see the proposal in the [magento/architecture](https://github.com/magento/architecture) repository.
